/*
 * Generated by gdbus-codegen 2.48.0. DO NOT EDIT.
 *
 * The license of this code is the same as for the source it was derived from.
 */

#ifdef HAVE_CONFIG_H
#  include "config.h"
#endif

#include "system_manager.h"

#include <string.h>
#ifdef G_OS_UNIX
#  include <gio/gunixfdlist.h>
#endif

typedef struct
{
  GDBusArgInfo parent_struct;
  gboolean use_gvariant;
} _ExtendedGDBusArgInfo;

typedef struct
{
  GDBusMethodInfo parent_struct;
  const gchar *signal_name;
  gboolean pass_fdlist;
} _ExtendedGDBusMethodInfo;

typedef struct
{
  GDBusSignalInfo parent_struct;
  const gchar *signal_name;
} _ExtendedGDBusSignalInfo;

typedef struct
{
  GDBusPropertyInfo parent_struct;
  const gchar *hyphen_name;
  gboolean use_gvariant;
} _ExtendedGDBusPropertyInfo;

typedef struct
{
  GDBusInterfaceInfo parent_struct;
  const gchar *hyphen_name;
} _ExtendedGDBusInterfaceInfo;

typedef struct
{
  const _ExtendedGDBusPropertyInfo *info;
  guint prop_id;
  GValue orig_value; /* the value before the change */
} ChangedProperty;

static void
_changed_property_free (ChangedProperty *data)
{
  g_value_unset (&data->orig_value);
  g_free (data);
}

static gboolean
_g_strv_equal0 (gchar **a, gchar **b)
{
  gboolean ret = FALSE;
  guint n;
  if (a == NULL && b == NULL)
    {
      ret = TRUE;
      goto out;
    }
  if (a == NULL || b == NULL)
    goto out;
  if (g_strv_length (a) != g_strv_length (b))
    goto out;
  for (n = 0; a[n] != NULL; n++)
    if (g_strcmp0 (a[n], b[n]) != 0)
      goto out;
  ret = TRUE;
out:
  return ret;
}

static gboolean
_g_variant_equal0 (GVariant *a, GVariant *b)
{
  gboolean ret = FALSE;
  if (a == NULL && b == NULL)
    {
      ret = TRUE;
      goto out;
    }
  if (a == NULL || b == NULL)
    goto out;
  ret = g_variant_equal (a, b);
out:
  return ret;
}

G_GNUC_UNUSED static gboolean
_g_value_equal (const GValue *a, const GValue *b)
{
  gboolean ret = FALSE;
  g_assert (G_VALUE_TYPE (a) == G_VALUE_TYPE (b));
  switch (G_VALUE_TYPE (a))
    {
      case G_TYPE_BOOLEAN:
        ret = (g_value_get_boolean (a) == g_value_get_boolean (b));
        break;
      case G_TYPE_UCHAR:
        ret = (g_value_get_uchar (a) == g_value_get_uchar (b));
        break;
      case G_TYPE_INT:
        ret = (g_value_get_int (a) == g_value_get_int (b));
        break;
      case G_TYPE_UINT:
        ret = (g_value_get_uint (a) == g_value_get_uint (b));
        break;
      case G_TYPE_INT64:
        ret = (g_value_get_int64 (a) == g_value_get_int64 (b));
        break;
      case G_TYPE_UINT64:
        ret = (g_value_get_uint64 (a) == g_value_get_uint64 (b));
        break;
      case G_TYPE_DOUBLE:
        {
          /* Avoid -Wfloat-equal warnings by doing a direct bit compare */
          gdouble da = g_value_get_double (a);
          gdouble db = g_value_get_double (b);
          ret = memcmp (&da, &db, sizeof (gdouble)) == 0;
        }
        break;
      case G_TYPE_STRING:
        ret = (g_strcmp0 (g_value_get_string (a), g_value_get_string (b)) == 0);
        break;
      case G_TYPE_VARIANT:
        ret = _g_variant_equal0 (g_value_get_variant (a), g_value_get_variant (b));
        break;
      default:
        if (G_VALUE_TYPE (a) == G_TYPE_STRV)
          ret = _g_strv_equal0 (g_value_get_boxed (a), g_value_get_boxed (b));
        else
          g_critical ("_g_value_equal() does not handle type %s", g_type_name (G_VALUE_TYPE (a)));
        break;
    }
  return ret;
}

/* ------------------------------------------------------------------------
 * Code for interface org.freedesktop.SystemManager.User
 * ------------------------------------------------------------------------
 */

/**
 * SECTION:SystemManagerUser
 * @title: SystemManagerUser
 * @short_description: Generated C code for the org.freedesktop.SystemManager.User D-Bus interface
 *
 * This section contains code for working with the <link linkend="gdbus-interface-org-freedesktop-SystemManager-User.top_of_page">org.freedesktop.SystemManager.User</link> D-Bus interface in C.
 */

/* ---- Introspection data for org.freedesktop.SystemManager.User ---- */

static const _ExtendedGDBusArgInfo _system_manager_user_method_info_auth_IN_ARG_username =
{
  {
    -1,
    (gchar *) "username",
    (gchar *) "s",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo _system_manager_user_method_info_auth_IN_ARG_password =
{
  {
    -1,
    (gchar *) "password",
    (gchar *) "s",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _system_manager_user_method_info_auth_IN_ARG_pointers[] =
{
  &_system_manager_user_method_info_auth_IN_ARG_username,
  &_system_manager_user_method_info_auth_IN_ARG_password,
  NULL
};

static const _ExtendedGDBusArgInfo _system_manager_user_method_info_auth_OUT_ARG_unnamed_arg2 =
{
  {
    -1,
    (gchar *) "unnamed_arg2",
    (gchar *) "b",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _system_manager_user_method_info_auth_OUT_ARG_pointers[] =
{
  &_system_manager_user_method_info_auth_OUT_ARG_unnamed_arg2,
  NULL
};

static const _ExtendedGDBusMethodInfo _system_manager_user_method_info_auth =
{
  {
    -1,
    (gchar *) "auth",
    (GDBusArgInfo **) &_system_manager_user_method_info_auth_IN_ARG_pointers,
    (GDBusArgInfo **) &_system_manager_user_method_info_auth_OUT_ARG_pointers,
    NULL
  },
  "handle-auth",
  FALSE
};

static const _ExtendedGDBusMethodInfo * const _system_manager_user_method_info_pointers[] =
{
  &_system_manager_user_method_info_auth,
  NULL
};

static const _ExtendedGDBusInterfaceInfo _system_manager_user_interface_info =
{
  {
    -1,
    (gchar *) "org.freedesktop.SystemManager.User",
    (GDBusMethodInfo **) &_system_manager_user_method_info_pointers,
    NULL,
    NULL,
    NULL
  },
  "system-manager-user",
};


/**
 * system_manager_user_interface_info:
 *
 * Gets a machine-readable description of the <link linkend="gdbus-interface-org-freedesktop-SystemManager-User.top_of_page">org.freedesktop.SystemManager.User</link> D-Bus interface.
 *
 * Returns: (transfer none): A #GDBusInterfaceInfo. Do not free.
 */
GDBusInterfaceInfo *
system_manager_user_interface_info (void)
{
  return (GDBusInterfaceInfo *) &_system_manager_user_interface_info.parent_struct;
}

/**
 * system_manager_user_override_properties:
 * @klass: The class structure for a #GObject<!-- -->-derived class.
 * @property_id_begin: The property id to assign to the first overridden property.
 *
 * Overrides all #GObject properties in the #SystemManagerUser interface for a concrete class.
 * The properties are overridden in the order they are defined.
 *
 * Returns: The last property id.
 */
guint
system_manager_user_override_properties (GObjectClass *klass, guint property_id_begin)
{
  return property_id_begin - 1;
}



/**
 * SystemManagerUser:
 *
 * Abstract interface type for the D-Bus interface <link linkend="gdbus-interface-org-freedesktop-SystemManager-User.top_of_page">org.freedesktop.SystemManager.User</link>.
 */

/**
 * SystemManagerUserIface:
 * @parent_iface: The parent interface.
 * @handle_auth: Handler for the #SystemManagerUser::handle-auth signal.
 *
 * Virtual table for the D-Bus interface <link linkend="gdbus-interface-org-freedesktop-SystemManager-User.top_of_page">org.freedesktop.SystemManager.User</link>.
 */

typedef SystemManagerUserIface SystemManagerUserInterface;
G_DEFINE_INTERFACE (SystemManagerUser, system_manager_user, G_TYPE_OBJECT);

static void
system_manager_user_default_init (SystemManagerUserIface *iface)
{
  /* GObject signals for incoming D-Bus method calls: */
  /**
   * SystemManagerUser::handle-auth:
   * @object: A #SystemManagerUser.
   * @invocation: A #GDBusMethodInvocation.
   * @arg_username: Argument passed by remote caller.
   * @arg_password: Argument passed by remote caller.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-org-freedesktop-SystemManager-User.auth">auth()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call system_manager_user_complete_auth() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-auth",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (SystemManagerUserIface, handle_auth),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    3,
    G_TYPE_DBUS_METHOD_INVOCATION, G_TYPE_STRING, G_TYPE_STRING);

}

/**
 * system_manager_user_call_auth:
 * @proxy: A #SystemManagerUserProxy.
 * @arg_username: Argument to pass with the method invocation.
 * @arg_password: Argument to pass with the method invocation.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-org-freedesktop-SystemManager-User.auth">auth()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call system_manager_user_call_auth_finish() to get the result of the operation.
 *
 * See system_manager_user_call_auth_sync() for the synchronous, blocking version of this method.
 */
void
system_manager_user_call_auth (
    SystemManagerUser *proxy,
    const gchar *arg_username,
    const gchar *arg_password,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "auth",
    g_variant_new ("(ss)",
                   arg_username,
                   arg_password),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * system_manager_user_call_auth_finish:
 * @proxy: A #SystemManagerUserProxy.
 * @out_unnamed_arg2: (out): Return location for return parameter or %NULL to ignore.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to system_manager_user_call_auth().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with system_manager_user_call_auth().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
system_manager_user_call_auth_finish (
    SystemManagerUser *proxy,
    gboolean *out_unnamed_arg2,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(b)",
                 out_unnamed_arg2);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * system_manager_user_call_auth_sync:
 * @proxy: A #SystemManagerUserProxy.
 * @arg_username: Argument to pass with the method invocation.
 * @arg_password: Argument to pass with the method invocation.
 * @out_unnamed_arg2: (out): Return location for return parameter or %NULL to ignore.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-org-freedesktop-SystemManager-User.auth">auth()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See system_manager_user_call_auth() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
system_manager_user_call_auth_sync (
    SystemManagerUser *proxy,
    const gchar *arg_username,
    const gchar *arg_password,
    gboolean *out_unnamed_arg2,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "auth",
    g_variant_new ("(ss)",
                   arg_username,
                   arg_password),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(b)",
                 out_unnamed_arg2);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * system_manager_user_complete_auth:
 * @object: A #SystemManagerUser.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 * @unnamed_arg2: Parameter to return.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-org-freedesktop-SystemManager-User.auth">auth()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
system_manager_user_complete_auth (
    SystemManagerUser *object,
    GDBusMethodInvocation *invocation,
    gboolean unnamed_arg2)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("(b)",
                   unnamed_arg2));
}

/* ------------------------------------------------------------------------ */

/**
 * SystemManagerUserProxy:
 *
 * The #SystemManagerUserProxy structure contains only private data and should only be accessed using the provided API.
 */

/**
 * SystemManagerUserProxyClass:
 * @parent_class: The parent class.
 *
 * Class structure for #SystemManagerUserProxy.
 */

struct _SystemManagerUserProxyPrivate
{
  GData *qdata;
};

static void system_manager_user_proxy_iface_init (SystemManagerUserIface *iface);

#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_38
G_DEFINE_TYPE_WITH_CODE (SystemManagerUserProxy, system_manager_user_proxy, G_TYPE_DBUS_PROXY,
                         G_ADD_PRIVATE (SystemManagerUserProxy)
                         G_IMPLEMENT_INTERFACE (TYPE_SYSTEM_MANAGER_USER, system_manager_user_proxy_iface_init));

#else
G_DEFINE_TYPE_WITH_CODE (SystemManagerUserProxy, system_manager_user_proxy, G_TYPE_DBUS_PROXY,
                         G_IMPLEMENT_INTERFACE (TYPE_SYSTEM_MANAGER_USER, system_manager_user_proxy_iface_init));

#endif
static void
system_manager_user_proxy_finalize (GObject *object)
{
  SystemManagerUserProxy *proxy = SYSTEM_MANAGER_USER_PROXY (object);
  g_datalist_clear (&proxy->priv->qdata);
  G_OBJECT_CLASS (system_manager_user_proxy_parent_class)->finalize (object);
}

static void
system_manager_user_proxy_get_property (GObject      *object,
  guint         prop_id,
  GValue       *value,
  GParamSpec   *pspec G_GNUC_UNUSED)
{
}

static void
system_manager_user_proxy_set_property (GObject      *object,
  guint         prop_id,
  const GValue *value,
  GParamSpec   *pspec G_GNUC_UNUSED)
{
}

static void
system_manager_user_proxy_g_signal (GDBusProxy *proxy,
  const gchar *sender_name G_GNUC_UNUSED,
  const gchar *signal_name,
  GVariant *parameters)
{
  _ExtendedGDBusSignalInfo *info;
  GVariantIter iter;
  GVariant *child;
  GValue *paramv;
  guint num_params;
  guint n;
  guint signal_id;
  info = (_ExtendedGDBusSignalInfo *) g_dbus_interface_info_lookup_signal ((GDBusInterfaceInfo *) &_system_manager_user_interface_info.parent_struct, signal_name);
  if (info == NULL)
    return;
  num_params = g_variant_n_children (parameters);
  paramv = g_new0 (GValue, num_params + 1);
  g_value_init (&paramv[0], TYPE_SYSTEM_MANAGER_USER);
  g_value_set_object (&paramv[0], proxy);
  g_variant_iter_init (&iter, parameters);
  n = 1;
  while ((child = g_variant_iter_next_value (&iter)) != NULL)
    {
      _ExtendedGDBusArgInfo *arg_info = (_ExtendedGDBusArgInfo *) info->parent_struct.args[n - 1];
      if (arg_info->use_gvariant)
        {
          g_value_init (&paramv[n], G_TYPE_VARIANT);
          g_value_set_variant (&paramv[n], child);
          n++;
        }
      else
        g_dbus_gvariant_to_gvalue (child, &paramv[n++]);
      g_variant_unref (child);
    }
  signal_id = g_signal_lookup (info->signal_name, TYPE_SYSTEM_MANAGER_USER);
  g_signal_emitv (paramv, signal_id, 0, NULL);
  for (n = 0; n < num_params + 1; n++)
    g_value_unset (&paramv[n]);
  g_free (paramv);
}

static void
system_manager_user_proxy_g_properties_changed (GDBusProxy *_proxy,
  GVariant *changed_properties,
  const gchar *const *invalidated_properties)
{
  SystemManagerUserProxy *proxy = SYSTEM_MANAGER_USER_PROXY (_proxy);
  guint n;
  const gchar *key;
  GVariantIter *iter;
  _ExtendedGDBusPropertyInfo *info;
  g_variant_get (changed_properties, "a{sv}", &iter);
  while (g_variant_iter_next (iter, "{&sv}", &key, NULL))
    {
      info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_system_manager_user_interface_info.parent_struct, key);
      g_datalist_remove_data (&proxy->priv->qdata, key);
      if (info != NULL)
        g_object_notify (G_OBJECT (proxy), info->hyphen_name);
    }
  g_variant_iter_free (iter);
  for (n = 0; invalidated_properties[n] != NULL; n++)
    {
      info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_system_manager_user_interface_info.parent_struct, invalidated_properties[n]);
      g_datalist_remove_data (&proxy->priv->qdata, invalidated_properties[n]);
      if (info != NULL)
        g_object_notify (G_OBJECT (proxy), info->hyphen_name);
    }
}

static void
system_manager_user_proxy_init (SystemManagerUserProxy *proxy)
{
#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_38
  proxy->priv = system_manager_user_proxy_get_instance_private (proxy);
#else
  proxy->priv = G_TYPE_INSTANCE_GET_PRIVATE (proxy, TYPE_SYSTEM_MANAGER_USER_PROXY, SystemManagerUserProxyPrivate);
#endif

  g_dbus_proxy_set_interface_info (G_DBUS_PROXY (proxy), system_manager_user_interface_info ());
}

static void
system_manager_user_proxy_class_init (SystemManagerUserProxyClass *klass)
{
  GObjectClass *gobject_class;
  GDBusProxyClass *proxy_class;

  gobject_class = G_OBJECT_CLASS (klass);
  gobject_class->finalize     = system_manager_user_proxy_finalize;
  gobject_class->get_property = system_manager_user_proxy_get_property;
  gobject_class->set_property = system_manager_user_proxy_set_property;

  proxy_class = G_DBUS_PROXY_CLASS (klass);
  proxy_class->g_signal = system_manager_user_proxy_g_signal;
  proxy_class->g_properties_changed = system_manager_user_proxy_g_properties_changed;

#if GLIB_VERSION_MAX_ALLOWED < GLIB_VERSION_2_38
  g_type_class_add_private (klass, sizeof (SystemManagerUserProxyPrivate));
#endif
}

static void
system_manager_user_proxy_iface_init (SystemManagerUserIface *iface)
{
}

/**
 * system_manager_user_proxy_new:
 * @connection: A #GDBusConnection.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: (allow-none): A bus name (well-known or unique) or %NULL if @connection is not a message bus connection.
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously creates a proxy for the D-Bus interface <link linkend="gdbus-interface-org-freedesktop-SystemManager-User.top_of_page">org.freedesktop.SystemManager.User</link>. See g_dbus_proxy_new() for more details.
 *
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call system_manager_user_proxy_new_finish() to get the result of the operation.
 *
 * See system_manager_user_proxy_new_sync() for the synchronous, blocking version of this constructor.
 */
void
system_manager_user_proxy_new (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data)
{
  g_async_initable_new_async (TYPE_SYSTEM_MANAGER_USER_PROXY, G_PRIORITY_DEFAULT, cancellable, callback, user_data, "g-flags", flags, "g-name", name, "g-connection", connection, "g-object-path", object_path, "g-interface-name", "org.freedesktop.SystemManager.User", NULL);
}

/**
 * system_manager_user_proxy_new_finish:
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to system_manager_user_proxy_new().
 * @error: Return location for error or %NULL
 *
 * Finishes an operation started with system_manager_user_proxy_new().
 *
 * Returns: (transfer full) (type SystemManagerUserProxy): The constructed proxy object or %NULL if @error is set.
 */
SystemManagerUser *
system_manager_user_proxy_new_finish (
    GAsyncResult        *res,
    GError             **error)
{
  GObject *ret;
  GObject *source_object;
  source_object = g_async_result_get_source_object (res);
  ret = g_async_initable_new_finish (G_ASYNC_INITABLE (source_object), res, error);
  g_object_unref (source_object);
  if (ret != NULL)
    return SYSTEM_MANAGER_USER (ret);
  else
    return NULL;
}

/**
 * system_manager_user_proxy_new_sync:
 * @connection: A #GDBusConnection.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: (allow-none): A bus name (well-known or unique) or %NULL if @connection is not a message bus connection.
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL
 *
 * Synchronously creates a proxy for the D-Bus interface <link linkend="gdbus-interface-org-freedesktop-SystemManager-User.top_of_page">org.freedesktop.SystemManager.User</link>. See g_dbus_proxy_new_sync() for more details.
 *
 * The calling thread is blocked until a reply is received.
 *
 * See system_manager_user_proxy_new() for the asynchronous version of this constructor.
 *
 * Returns: (transfer full) (type SystemManagerUserProxy): The constructed proxy object or %NULL if @error is set.
 */
SystemManagerUser *
system_manager_user_proxy_new_sync (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error)
{
  GInitable *ret;
  ret = g_initable_new (TYPE_SYSTEM_MANAGER_USER_PROXY, cancellable, error, "g-flags", flags, "g-name", name, "g-connection", connection, "g-object-path", object_path, "g-interface-name", "org.freedesktop.SystemManager.User", NULL);
  if (ret != NULL)
    return SYSTEM_MANAGER_USER (ret);
  else
    return NULL;
}


/**
 * system_manager_user_proxy_new_for_bus:
 * @bus_type: A #GBusType.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: A bus name (well-known or unique).
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied.
 * @user_data: User data to pass to @callback.
 *
 * Like system_manager_user_proxy_new() but takes a #GBusType instead of a #GDBusConnection.
 *
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call system_manager_user_proxy_new_for_bus_finish() to get the result of the operation.
 *
 * See system_manager_user_proxy_new_for_bus_sync() for the synchronous, blocking version of this constructor.
 */
void
system_manager_user_proxy_new_for_bus (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data)
{
  g_async_initable_new_async (TYPE_SYSTEM_MANAGER_USER_PROXY, G_PRIORITY_DEFAULT, cancellable, callback, user_data, "g-flags", flags, "g-name", name, "g-bus-type", bus_type, "g-object-path", object_path, "g-interface-name", "org.freedesktop.SystemManager.User", NULL);
}

/**
 * system_manager_user_proxy_new_for_bus_finish:
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to system_manager_user_proxy_new_for_bus().
 * @error: Return location for error or %NULL
 *
 * Finishes an operation started with system_manager_user_proxy_new_for_bus().
 *
 * Returns: (transfer full) (type SystemManagerUserProxy): The constructed proxy object or %NULL if @error is set.
 */
SystemManagerUser *
system_manager_user_proxy_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error)
{
  GObject *ret;
  GObject *source_object;
  source_object = g_async_result_get_source_object (res);
  ret = g_async_initable_new_finish (G_ASYNC_INITABLE (source_object), res, error);
  g_object_unref (source_object);
  if (ret != NULL)
    return SYSTEM_MANAGER_USER (ret);
  else
    return NULL;
}

/**
 * system_manager_user_proxy_new_for_bus_sync:
 * @bus_type: A #GBusType.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: A bus name (well-known or unique).
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL
 *
 * Like system_manager_user_proxy_new_sync() but takes a #GBusType instead of a #GDBusConnection.
 *
 * The calling thread is blocked until a reply is received.
 *
 * See system_manager_user_proxy_new_for_bus() for the asynchronous version of this constructor.
 *
 * Returns: (transfer full) (type SystemManagerUserProxy): The constructed proxy object or %NULL if @error is set.
 */
SystemManagerUser *
system_manager_user_proxy_new_for_bus_sync (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error)
{
  GInitable *ret;
  ret = g_initable_new (TYPE_SYSTEM_MANAGER_USER_PROXY, cancellable, error, "g-flags", flags, "g-name", name, "g-bus-type", bus_type, "g-object-path", object_path, "g-interface-name", "org.freedesktop.SystemManager.User", NULL);
  if (ret != NULL)
    return SYSTEM_MANAGER_USER (ret);
  else
    return NULL;
}


/* ------------------------------------------------------------------------ */

/**
 * SystemManagerUserSkeleton:
 *
 * The #SystemManagerUserSkeleton structure contains only private data and should only be accessed using the provided API.
 */

/**
 * SystemManagerUserSkeletonClass:
 * @parent_class: The parent class.
 *
 * Class structure for #SystemManagerUserSkeleton.
 */

struct _SystemManagerUserSkeletonPrivate
{
  GValue *properties;
  GList *changed_properties;
  GSource *changed_properties_idle_source;
  GMainContext *context;
  GMutex lock;
};

static void
_system_manager_user_skeleton_handle_method_call (
  GDBusConnection *connection G_GNUC_UNUSED,
  const gchar *sender G_GNUC_UNUSED,
  const gchar *object_path G_GNUC_UNUSED,
  const gchar *interface_name,
  const gchar *method_name,
  GVariant *parameters,
  GDBusMethodInvocation *invocation,
  gpointer user_data)
{
  SystemManagerUserSkeleton *skeleton = SYSTEM_MANAGER_USER_SKELETON (user_data);
  _ExtendedGDBusMethodInfo *info;
  GVariantIter iter;
  GVariant *child;
  GValue *paramv;
  guint num_params;
  guint num_extra;
  guint n;
  guint signal_id;
  GValue return_value = G_VALUE_INIT;
  info = (_ExtendedGDBusMethodInfo *) g_dbus_method_invocation_get_method_info (invocation);
  g_assert (info != NULL);
  num_params = g_variant_n_children (parameters);
  num_extra = info->pass_fdlist ? 3 : 2;  paramv = g_new0 (GValue, num_params + num_extra);
  n = 0;
  g_value_init (&paramv[n], TYPE_SYSTEM_MANAGER_USER);
  g_value_set_object (&paramv[n++], skeleton);
  g_value_init (&paramv[n], G_TYPE_DBUS_METHOD_INVOCATION);
  g_value_set_object (&paramv[n++], invocation);
  if (info->pass_fdlist)
    {
#ifdef G_OS_UNIX
      g_value_init (&paramv[n], G_TYPE_UNIX_FD_LIST);
      g_value_set_object (&paramv[n++], g_dbus_message_get_unix_fd_list (g_dbus_method_invocation_get_message (invocation)));
#else
      g_assert_not_reached ();
#endif
    }
  g_variant_iter_init (&iter, parameters);
  while ((child = g_variant_iter_next_value (&iter)) != NULL)
    {
      _ExtendedGDBusArgInfo *arg_info = (_ExtendedGDBusArgInfo *) info->parent_struct.in_args[n - num_extra];
      if (arg_info->use_gvariant)
        {
          g_value_init (&paramv[n], G_TYPE_VARIANT);
          g_value_set_variant (&paramv[n], child);
          n++;
        }
      else
        g_dbus_gvariant_to_gvalue (child, &paramv[n++]);
      g_variant_unref (child);
    }
  signal_id = g_signal_lookup (info->signal_name, TYPE_SYSTEM_MANAGER_USER);
  g_value_init (&return_value, G_TYPE_BOOLEAN);
  g_signal_emitv (paramv, signal_id, 0, &return_value);
  if (!g_value_get_boolean (&return_value))
    g_dbus_method_invocation_return_error (invocation, G_DBUS_ERROR, G_DBUS_ERROR_UNKNOWN_METHOD, "Method %s is not implemented on interface %s", method_name, interface_name);
  g_value_unset (&return_value);
  for (n = 0; n < num_params + num_extra; n++)
    g_value_unset (&paramv[n]);
  g_free (paramv);
}

static GVariant *
_system_manager_user_skeleton_handle_get_property (
  GDBusConnection *connection G_GNUC_UNUSED,
  const gchar *sender G_GNUC_UNUSED,
  const gchar *object_path G_GNUC_UNUSED,
  const gchar *interface_name G_GNUC_UNUSED,
  const gchar *property_name,
  GError **error,
  gpointer user_data)
{
  SystemManagerUserSkeleton *skeleton = SYSTEM_MANAGER_USER_SKELETON (user_data);
  GValue value = G_VALUE_INIT;
  GParamSpec *pspec;
  _ExtendedGDBusPropertyInfo *info;
  GVariant *ret;
  ret = NULL;
  info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_system_manager_user_interface_info.parent_struct, property_name);
  g_assert (info != NULL);
  pspec = g_object_class_find_property (G_OBJECT_GET_CLASS (skeleton), info->hyphen_name);
  if (pspec == NULL)
    {
      g_set_error (error, G_DBUS_ERROR, G_DBUS_ERROR_INVALID_ARGS, "No property with name %s", property_name);
    }
  else
    {
      g_value_init (&value, pspec->value_type);
      g_object_get_property (G_OBJECT (skeleton), info->hyphen_name, &value);
      ret = g_dbus_gvalue_to_gvariant (&value, G_VARIANT_TYPE (info->parent_struct.signature));
      g_value_unset (&value);
    }
  return ret;
}

static gboolean
_system_manager_user_skeleton_handle_set_property (
  GDBusConnection *connection G_GNUC_UNUSED,
  const gchar *sender G_GNUC_UNUSED,
  const gchar *object_path G_GNUC_UNUSED,
  const gchar *interface_name G_GNUC_UNUSED,
  const gchar *property_name,
  GVariant *variant,
  GError **error,
  gpointer user_data)
{
  SystemManagerUserSkeleton *skeleton = SYSTEM_MANAGER_USER_SKELETON (user_data);
  GValue value = G_VALUE_INIT;
  GParamSpec *pspec;
  _ExtendedGDBusPropertyInfo *info;
  gboolean ret;
  ret = FALSE;
  info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_system_manager_user_interface_info.parent_struct, property_name);
  g_assert (info != NULL);
  pspec = g_object_class_find_property (G_OBJECT_GET_CLASS (skeleton), info->hyphen_name);
  if (pspec == NULL)
    {
      g_set_error (error, G_DBUS_ERROR, G_DBUS_ERROR_INVALID_ARGS, "No property with name %s", property_name);
    }
  else
    {
      if (info->use_gvariant)
        g_value_set_variant (&value, variant);
      else
        g_dbus_gvariant_to_gvalue (variant, &value);
      g_object_set_property (G_OBJECT (skeleton), info->hyphen_name, &value);
      g_value_unset (&value);
      ret = TRUE;
    }
  return ret;
}

static const GDBusInterfaceVTable _system_manager_user_skeleton_vtable =
{
  _system_manager_user_skeleton_handle_method_call,
  _system_manager_user_skeleton_handle_get_property,
  _system_manager_user_skeleton_handle_set_property,
  {NULL}
};

static GDBusInterfaceInfo *
system_manager_user_skeleton_dbus_interface_get_info (GDBusInterfaceSkeleton *skeleton G_GNUC_UNUSED)
{
  return system_manager_user_interface_info ();
}

static GDBusInterfaceVTable *
system_manager_user_skeleton_dbus_interface_get_vtable (GDBusInterfaceSkeleton *skeleton G_GNUC_UNUSED)
{
  return (GDBusInterfaceVTable *) &_system_manager_user_skeleton_vtable;
}

static GVariant *
system_manager_user_skeleton_dbus_interface_get_properties (GDBusInterfaceSkeleton *_skeleton)
{
  SystemManagerUserSkeleton *skeleton = SYSTEM_MANAGER_USER_SKELETON (_skeleton);

  GVariantBuilder builder;
  guint n;
  g_variant_builder_init (&builder, G_VARIANT_TYPE ("a{sv}"));
  if (_system_manager_user_interface_info.parent_struct.properties == NULL)
    goto out;
  for (n = 0; _system_manager_user_interface_info.parent_struct.properties[n] != NULL; n++)
    {
      GDBusPropertyInfo *info = _system_manager_user_interface_info.parent_struct.properties[n];
      if (info->flags & G_DBUS_PROPERTY_INFO_FLAGS_READABLE)
        {
          GVariant *value;
          value = _system_manager_user_skeleton_handle_get_property (g_dbus_interface_skeleton_get_connection (G_DBUS_INTERFACE_SKELETON (skeleton)), NULL, g_dbus_interface_skeleton_get_object_path (G_DBUS_INTERFACE_SKELETON (skeleton)), "org.freedesktop.SystemManager.User", info->name, NULL, skeleton);
          if (value != NULL)
            {
              g_variant_take_ref (value);
              g_variant_builder_add (&builder, "{sv}", info->name, value);
              g_variant_unref (value);
            }
        }
    }
out:
  return g_variant_builder_end (&builder);
}

static void
system_manager_user_skeleton_dbus_interface_flush (GDBusInterfaceSkeleton *_skeleton)
{
}

static void system_manager_user_skeleton_iface_init (SystemManagerUserIface *iface);
#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_38
G_DEFINE_TYPE_WITH_CODE (SystemManagerUserSkeleton, system_manager_user_skeleton, G_TYPE_DBUS_INTERFACE_SKELETON,
                         G_ADD_PRIVATE (SystemManagerUserSkeleton)
                         G_IMPLEMENT_INTERFACE (TYPE_SYSTEM_MANAGER_USER, system_manager_user_skeleton_iface_init));

#else
G_DEFINE_TYPE_WITH_CODE (SystemManagerUserSkeleton, system_manager_user_skeleton, G_TYPE_DBUS_INTERFACE_SKELETON,
                         G_IMPLEMENT_INTERFACE (TYPE_SYSTEM_MANAGER_USER, system_manager_user_skeleton_iface_init));

#endif
static void
system_manager_user_skeleton_finalize (GObject *object)
{
  SystemManagerUserSkeleton *skeleton = SYSTEM_MANAGER_USER_SKELETON (object);
  g_list_free_full (skeleton->priv->changed_properties, (GDestroyNotify) _changed_property_free);
  if (skeleton->priv->changed_properties_idle_source != NULL)
    g_source_destroy (skeleton->priv->changed_properties_idle_source);
  g_main_context_unref (skeleton->priv->context);
  g_mutex_clear (&skeleton->priv->lock);
  G_OBJECT_CLASS (system_manager_user_skeleton_parent_class)->finalize (object);
}

static void
system_manager_user_skeleton_init (SystemManagerUserSkeleton *skeleton)
{
#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_38
  skeleton->priv = system_manager_user_skeleton_get_instance_private (skeleton);
#else
  skeleton->priv = G_TYPE_INSTANCE_GET_PRIVATE (skeleton, TYPE_SYSTEM_MANAGER_USER_SKELETON, SystemManagerUserSkeletonPrivate);
#endif

  g_mutex_init (&skeleton->priv->lock);
  skeleton->priv->context = g_main_context_ref_thread_default ();
}

static void
system_manager_user_skeleton_class_init (SystemManagerUserSkeletonClass *klass)
{
  GObjectClass *gobject_class;
  GDBusInterfaceSkeletonClass *skeleton_class;

  gobject_class = G_OBJECT_CLASS (klass);
  gobject_class->finalize = system_manager_user_skeleton_finalize;

  skeleton_class = G_DBUS_INTERFACE_SKELETON_CLASS (klass);
  skeleton_class->get_info = system_manager_user_skeleton_dbus_interface_get_info;
  skeleton_class->get_properties = system_manager_user_skeleton_dbus_interface_get_properties;
  skeleton_class->flush = system_manager_user_skeleton_dbus_interface_flush;
  skeleton_class->get_vtable = system_manager_user_skeleton_dbus_interface_get_vtable;

#if GLIB_VERSION_MAX_ALLOWED < GLIB_VERSION_2_38
  g_type_class_add_private (klass, sizeof (SystemManagerUserSkeletonPrivate));
#endif
}

static void
system_manager_user_skeleton_iface_init (SystemManagerUserIface *iface)
{
}

/**
 * system_manager_user_skeleton_new:
 *
 * Creates a skeleton object for the D-Bus interface <link linkend="gdbus-interface-org-freedesktop-SystemManager-User.top_of_page">org.freedesktop.SystemManager.User</link>.
 *
 * Returns: (transfer full) (type SystemManagerUserSkeleton): The skeleton object.
 */
SystemManagerUser *
system_manager_user_skeleton_new (void)
{
  return SYSTEM_MANAGER_USER (g_object_new (TYPE_SYSTEM_MANAGER_USER_SKELETON, NULL));
}

/* ------------------------------------------------------------------------
 * Code for interface org.freedesktop.SystemManager.Network
 * ------------------------------------------------------------------------
 */

/**
 * SECTION:SystemManagerNetwork
 * @title: SystemManagerNetwork
 * @short_description: Generated C code for the org.freedesktop.SystemManager.Network D-Bus interface
 *
 * This section contains code for working with the <link linkend="gdbus-interface-org-freedesktop-SystemManager-Network.top_of_page">org.freedesktop.SystemManager.Network</link> D-Bus interface in C.
 */

/* ---- Introspection data for org.freedesktop.SystemManager.Network ---- */

static const _ExtendedGDBusArgInfo _system_manager_network_method_info_connect_IN_ARG_interface =
{
  {
    -1,
    (gchar *) "interface",
    (gchar *) "s",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _system_manager_network_method_info_connect_IN_ARG_pointers[] =
{
  &_system_manager_network_method_info_connect_IN_ARG_interface,
  NULL
};

static const _ExtendedGDBusArgInfo _system_manager_network_method_info_connect_OUT_ARG_unnamed_arg1 =
{
  {
    -1,
    (gchar *) "unnamed_arg1",
    (gchar *) "b",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _system_manager_network_method_info_connect_OUT_ARG_pointers[] =
{
  &_system_manager_network_method_info_connect_OUT_ARG_unnamed_arg1,
  NULL
};

static const _ExtendedGDBusMethodInfo _system_manager_network_method_info_connect =
{
  {
    -1,
    (gchar *) "connect",
    (GDBusArgInfo **) &_system_manager_network_method_info_connect_IN_ARG_pointers,
    (GDBusArgInfo **) &_system_manager_network_method_info_connect_OUT_ARG_pointers,
    NULL
  },
  "handle-connect",
  FALSE
};

static const _ExtendedGDBusArgInfo _system_manager_network_method_info_status_IN_ARG_interface =
{
  {
    -1,
    (gchar *) "interface",
    (gchar *) "s",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _system_manager_network_method_info_status_IN_ARG_pointers[] =
{
  &_system_manager_network_method_info_status_IN_ARG_interface,
  NULL
};

static const _ExtendedGDBusArgInfo _system_manager_network_method_info_status_OUT_ARG_unnamed_arg1 =
{
  {
    -1,
    (gchar *) "unnamed_arg1",
    (gchar *) "t",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _system_manager_network_method_info_status_OUT_ARG_pointers[] =
{
  &_system_manager_network_method_info_status_OUT_ARG_unnamed_arg1,
  NULL
};

static const _ExtendedGDBusMethodInfo _system_manager_network_method_info_status =
{
  {
    -1,
    (gchar *) "status",
    (GDBusArgInfo **) &_system_manager_network_method_info_status_IN_ARG_pointers,
    (GDBusArgInfo **) &_system_manager_network_method_info_status_OUT_ARG_pointers,
    NULL
  },
  "handle-status",
  FALSE
};

static const _ExtendedGDBusMethodInfo * const _system_manager_network_method_info_pointers[] =
{
  &_system_manager_network_method_info_connect,
  &_system_manager_network_method_info_status,
  NULL
};

static const _ExtendedGDBusInterfaceInfo _system_manager_network_interface_info =
{
  {
    -1,
    (gchar *) "org.freedesktop.SystemManager.Network",
    (GDBusMethodInfo **) &_system_manager_network_method_info_pointers,
    NULL,
    NULL,
    NULL
  },
  "system-manager-network",
};


/**
 * system_manager_network_interface_info:
 *
 * Gets a machine-readable description of the <link linkend="gdbus-interface-org-freedesktop-SystemManager-Network.top_of_page">org.freedesktop.SystemManager.Network</link> D-Bus interface.
 *
 * Returns: (transfer none): A #GDBusInterfaceInfo. Do not free.
 */
GDBusInterfaceInfo *
system_manager_network_interface_info (void)
{
  return (GDBusInterfaceInfo *) &_system_manager_network_interface_info.parent_struct;
}

/**
 * system_manager_network_override_properties:
 * @klass: The class structure for a #GObject<!-- -->-derived class.
 * @property_id_begin: The property id to assign to the first overridden property.
 *
 * Overrides all #GObject properties in the #SystemManagerNetwork interface for a concrete class.
 * The properties are overridden in the order they are defined.
 *
 * Returns: The last property id.
 */
guint
system_manager_network_override_properties (GObjectClass *klass, guint property_id_begin)
{
  return property_id_begin - 1;
}



/**
 * SystemManagerNetwork:
 *
 * Abstract interface type for the D-Bus interface <link linkend="gdbus-interface-org-freedesktop-SystemManager-Network.top_of_page">org.freedesktop.SystemManager.Network</link>.
 */

/**
 * SystemManagerNetworkIface:
 * @parent_iface: The parent interface.
 * @handle_connect: Handler for the #SystemManagerNetwork::handle-connect signal.
 * @handle_status: Handler for the #SystemManagerNetwork::handle-status signal.
 *
 * Virtual table for the D-Bus interface <link linkend="gdbus-interface-org-freedesktop-SystemManager-Network.top_of_page">org.freedesktop.SystemManager.Network</link>.
 */

typedef SystemManagerNetworkIface SystemManagerNetworkInterface;
G_DEFINE_INTERFACE (SystemManagerNetwork, system_manager_network, G_TYPE_OBJECT);

static void
system_manager_network_default_init (SystemManagerNetworkIface *iface)
{
  /* GObject signals for incoming D-Bus method calls: */
  /**
   * SystemManagerNetwork::handle-connect:
   * @object: A #SystemManagerNetwork.
   * @invocation: A #GDBusMethodInvocation.
   * @arg_interface: Argument passed by remote caller.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-org-freedesktop-SystemManager-Network.connect">connect()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call system_manager_network_complete_connect() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-connect",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (SystemManagerNetworkIface, handle_connect),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    2,
    G_TYPE_DBUS_METHOD_INVOCATION, G_TYPE_STRING);

  /**
   * SystemManagerNetwork::handle-status:
   * @object: A #SystemManagerNetwork.
   * @invocation: A #GDBusMethodInvocation.
   * @arg_interface: Argument passed by remote caller.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-org-freedesktop-SystemManager-Network.status">status()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call system_manager_network_complete_status() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-status",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (SystemManagerNetworkIface, handle_status),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    2,
    G_TYPE_DBUS_METHOD_INVOCATION, G_TYPE_STRING);

}

/**
 * system_manager_network_call_connect:
 * @proxy: A #SystemManagerNetworkProxy.
 * @arg_interface: Argument to pass with the method invocation.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-org-freedesktop-SystemManager-Network.connect">connect()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call system_manager_network_call_connect_finish() to get the result of the operation.
 *
 * See system_manager_network_call_connect_sync() for the synchronous, blocking version of this method.
 */
void
system_manager_network_call_connect (
    SystemManagerNetwork *proxy,
    const gchar *arg_interface,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "connect",
    g_variant_new ("(s)",
                   arg_interface),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * system_manager_network_call_connect_finish:
 * @proxy: A #SystemManagerNetworkProxy.
 * @out_unnamed_arg1: (out): Return location for return parameter or %NULL to ignore.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to system_manager_network_call_connect().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with system_manager_network_call_connect().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
system_manager_network_call_connect_finish (
    SystemManagerNetwork *proxy,
    gboolean *out_unnamed_arg1,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(b)",
                 out_unnamed_arg1);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * system_manager_network_call_connect_sync:
 * @proxy: A #SystemManagerNetworkProxy.
 * @arg_interface: Argument to pass with the method invocation.
 * @out_unnamed_arg1: (out): Return location for return parameter or %NULL to ignore.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-org-freedesktop-SystemManager-Network.connect">connect()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See system_manager_network_call_connect() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
system_manager_network_call_connect_sync (
    SystemManagerNetwork *proxy,
    const gchar *arg_interface,
    gboolean *out_unnamed_arg1,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "connect",
    g_variant_new ("(s)",
                   arg_interface),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(b)",
                 out_unnamed_arg1);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * system_manager_network_call_status:
 * @proxy: A #SystemManagerNetworkProxy.
 * @arg_interface: Argument to pass with the method invocation.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-org-freedesktop-SystemManager-Network.status">status()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call system_manager_network_call_status_finish() to get the result of the operation.
 *
 * See system_manager_network_call_status_sync() for the synchronous, blocking version of this method.
 */
void
system_manager_network_call_status (
    SystemManagerNetwork *proxy,
    const gchar *arg_interface,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "status",
    g_variant_new ("(s)",
                   arg_interface),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * system_manager_network_call_status_finish:
 * @proxy: A #SystemManagerNetworkProxy.
 * @out_unnamed_arg1: (out): Return location for return parameter or %NULL to ignore.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to system_manager_network_call_status().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with system_manager_network_call_status().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
system_manager_network_call_status_finish (
    SystemManagerNetwork *proxy,
    guint64 *out_unnamed_arg1,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(t)",
                 out_unnamed_arg1);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * system_manager_network_call_status_sync:
 * @proxy: A #SystemManagerNetworkProxy.
 * @arg_interface: Argument to pass with the method invocation.
 * @out_unnamed_arg1: (out): Return location for return parameter or %NULL to ignore.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-org-freedesktop-SystemManager-Network.status">status()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See system_manager_network_call_status() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
system_manager_network_call_status_sync (
    SystemManagerNetwork *proxy,
    const gchar *arg_interface,
    guint64 *out_unnamed_arg1,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "status",
    g_variant_new ("(s)",
                   arg_interface),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(t)",
                 out_unnamed_arg1);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * system_manager_network_complete_connect:
 * @object: A #SystemManagerNetwork.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 * @unnamed_arg1: Parameter to return.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-org-freedesktop-SystemManager-Network.connect">connect()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
system_manager_network_complete_connect (
    SystemManagerNetwork *object,
    GDBusMethodInvocation *invocation,
    gboolean unnamed_arg1)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("(b)",
                   unnamed_arg1));
}

/**
 * system_manager_network_complete_status:
 * @object: A #SystemManagerNetwork.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 * @unnamed_arg1: Parameter to return.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-org-freedesktop-SystemManager-Network.status">status()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
system_manager_network_complete_status (
    SystemManagerNetwork *object,
    GDBusMethodInvocation *invocation,
    guint64 unnamed_arg1)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("(t)",
                   unnamed_arg1));
}

/* ------------------------------------------------------------------------ */

/**
 * SystemManagerNetworkProxy:
 *
 * The #SystemManagerNetworkProxy structure contains only private data and should only be accessed using the provided API.
 */

/**
 * SystemManagerNetworkProxyClass:
 * @parent_class: The parent class.
 *
 * Class structure for #SystemManagerNetworkProxy.
 */

struct _SystemManagerNetworkProxyPrivate
{
  GData *qdata;
};

static void system_manager_network_proxy_iface_init (SystemManagerNetworkIface *iface);

#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_38
G_DEFINE_TYPE_WITH_CODE (SystemManagerNetworkProxy, system_manager_network_proxy, G_TYPE_DBUS_PROXY,
                         G_ADD_PRIVATE (SystemManagerNetworkProxy)
                         G_IMPLEMENT_INTERFACE (TYPE_SYSTEM_MANAGER_NETWORK, system_manager_network_proxy_iface_init));

#else
G_DEFINE_TYPE_WITH_CODE (SystemManagerNetworkProxy, system_manager_network_proxy, G_TYPE_DBUS_PROXY,
                         G_IMPLEMENT_INTERFACE (TYPE_SYSTEM_MANAGER_NETWORK, system_manager_network_proxy_iface_init));

#endif
static void
system_manager_network_proxy_finalize (GObject *object)
{
  SystemManagerNetworkProxy *proxy = SYSTEM_MANAGER_NETWORK_PROXY (object);
  g_datalist_clear (&proxy->priv->qdata);
  G_OBJECT_CLASS (system_manager_network_proxy_parent_class)->finalize (object);
}

static void
system_manager_network_proxy_get_property (GObject      *object,
  guint         prop_id,
  GValue       *value,
  GParamSpec   *pspec G_GNUC_UNUSED)
{
}

static void
system_manager_network_proxy_set_property (GObject      *object,
  guint         prop_id,
  const GValue *value,
  GParamSpec   *pspec G_GNUC_UNUSED)
{
}

static void
system_manager_network_proxy_g_signal (GDBusProxy *proxy,
  const gchar *sender_name G_GNUC_UNUSED,
  const gchar *signal_name,
  GVariant *parameters)
{
  _ExtendedGDBusSignalInfo *info;
  GVariantIter iter;
  GVariant *child;
  GValue *paramv;
  guint num_params;
  guint n;
  guint signal_id;
  info = (_ExtendedGDBusSignalInfo *) g_dbus_interface_info_lookup_signal ((GDBusInterfaceInfo *) &_system_manager_network_interface_info.parent_struct, signal_name);
  if (info == NULL)
    return;
  num_params = g_variant_n_children (parameters);
  paramv = g_new0 (GValue, num_params + 1);
  g_value_init (&paramv[0], TYPE_SYSTEM_MANAGER_NETWORK);
  g_value_set_object (&paramv[0], proxy);
  g_variant_iter_init (&iter, parameters);
  n = 1;
  while ((child = g_variant_iter_next_value (&iter)) != NULL)
    {
      _ExtendedGDBusArgInfo *arg_info = (_ExtendedGDBusArgInfo *) info->parent_struct.args[n - 1];
      if (arg_info->use_gvariant)
        {
          g_value_init (&paramv[n], G_TYPE_VARIANT);
          g_value_set_variant (&paramv[n], child);
          n++;
        }
      else
        g_dbus_gvariant_to_gvalue (child, &paramv[n++]);
      g_variant_unref (child);
    }
  signal_id = g_signal_lookup (info->signal_name, TYPE_SYSTEM_MANAGER_NETWORK);
  g_signal_emitv (paramv, signal_id, 0, NULL);
  for (n = 0; n < num_params + 1; n++)
    g_value_unset (&paramv[n]);
  g_free (paramv);
}

static void
system_manager_network_proxy_g_properties_changed (GDBusProxy *_proxy,
  GVariant *changed_properties,
  const gchar *const *invalidated_properties)
{
  SystemManagerNetworkProxy *proxy = SYSTEM_MANAGER_NETWORK_PROXY (_proxy);
  guint n;
  const gchar *key;
  GVariantIter *iter;
  _ExtendedGDBusPropertyInfo *info;
  g_variant_get (changed_properties, "a{sv}", &iter);
  while (g_variant_iter_next (iter, "{&sv}", &key, NULL))
    {
      info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_system_manager_network_interface_info.parent_struct, key);
      g_datalist_remove_data (&proxy->priv->qdata, key);
      if (info != NULL)
        g_object_notify (G_OBJECT (proxy), info->hyphen_name);
    }
  g_variant_iter_free (iter);
  for (n = 0; invalidated_properties[n] != NULL; n++)
    {
      info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_system_manager_network_interface_info.parent_struct, invalidated_properties[n]);
      g_datalist_remove_data (&proxy->priv->qdata, invalidated_properties[n]);
      if (info != NULL)
        g_object_notify (G_OBJECT (proxy), info->hyphen_name);
    }
}

static void
system_manager_network_proxy_init (SystemManagerNetworkProxy *proxy)
{
#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_38
  proxy->priv = system_manager_network_proxy_get_instance_private (proxy);
#else
  proxy->priv = G_TYPE_INSTANCE_GET_PRIVATE (proxy, TYPE_SYSTEM_MANAGER_NETWORK_PROXY, SystemManagerNetworkProxyPrivate);
#endif

  g_dbus_proxy_set_interface_info (G_DBUS_PROXY (proxy), system_manager_network_interface_info ());
}

static void
system_manager_network_proxy_class_init (SystemManagerNetworkProxyClass *klass)
{
  GObjectClass *gobject_class;
  GDBusProxyClass *proxy_class;

  gobject_class = G_OBJECT_CLASS (klass);
  gobject_class->finalize     = system_manager_network_proxy_finalize;
  gobject_class->get_property = system_manager_network_proxy_get_property;
  gobject_class->set_property = system_manager_network_proxy_set_property;

  proxy_class = G_DBUS_PROXY_CLASS (klass);
  proxy_class->g_signal = system_manager_network_proxy_g_signal;
  proxy_class->g_properties_changed = system_manager_network_proxy_g_properties_changed;

#if GLIB_VERSION_MAX_ALLOWED < GLIB_VERSION_2_38
  g_type_class_add_private (klass, sizeof (SystemManagerNetworkProxyPrivate));
#endif
}

static void
system_manager_network_proxy_iface_init (SystemManagerNetworkIface *iface)
{
}

/**
 * system_manager_network_proxy_new:
 * @connection: A #GDBusConnection.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: (allow-none): A bus name (well-known or unique) or %NULL if @connection is not a message bus connection.
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously creates a proxy for the D-Bus interface <link linkend="gdbus-interface-org-freedesktop-SystemManager-Network.top_of_page">org.freedesktop.SystemManager.Network</link>. See g_dbus_proxy_new() for more details.
 *
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call system_manager_network_proxy_new_finish() to get the result of the operation.
 *
 * See system_manager_network_proxy_new_sync() for the synchronous, blocking version of this constructor.
 */
void
system_manager_network_proxy_new (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data)
{
  g_async_initable_new_async (TYPE_SYSTEM_MANAGER_NETWORK_PROXY, G_PRIORITY_DEFAULT, cancellable, callback, user_data, "g-flags", flags, "g-name", name, "g-connection", connection, "g-object-path", object_path, "g-interface-name", "org.freedesktop.SystemManager.Network", NULL);
}

/**
 * system_manager_network_proxy_new_finish:
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to system_manager_network_proxy_new().
 * @error: Return location for error or %NULL
 *
 * Finishes an operation started with system_manager_network_proxy_new().
 *
 * Returns: (transfer full) (type SystemManagerNetworkProxy): The constructed proxy object or %NULL if @error is set.
 */
SystemManagerNetwork *
system_manager_network_proxy_new_finish (
    GAsyncResult        *res,
    GError             **error)
{
  GObject *ret;
  GObject *source_object;
  source_object = g_async_result_get_source_object (res);
  ret = g_async_initable_new_finish (G_ASYNC_INITABLE (source_object), res, error);
  g_object_unref (source_object);
  if (ret != NULL)
    return SYSTEM_MANAGER_NETWORK (ret);
  else
    return NULL;
}

/**
 * system_manager_network_proxy_new_sync:
 * @connection: A #GDBusConnection.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: (allow-none): A bus name (well-known or unique) or %NULL if @connection is not a message bus connection.
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL
 *
 * Synchronously creates a proxy for the D-Bus interface <link linkend="gdbus-interface-org-freedesktop-SystemManager-Network.top_of_page">org.freedesktop.SystemManager.Network</link>. See g_dbus_proxy_new_sync() for more details.
 *
 * The calling thread is blocked until a reply is received.
 *
 * See system_manager_network_proxy_new() for the asynchronous version of this constructor.
 *
 * Returns: (transfer full) (type SystemManagerNetworkProxy): The constructed proxy object or %NULL if @error is set.
 */
SystemManagerNetwork *
system_manager_network_proxy_new_sync (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error)
{
  GInitable *ret;
  ret = g_initable_new (TYPE_SYSTEM_MANAGER_NETWORK_PROXY, cancellable, error, "g-flags", flags, "g-name", name, "g-connection", connection, "g-object-path", object_path, "g-interface-name", "org.freedesktop.SystemManager.Network", NULL);
  if (ret != NULL)
    return SYSTEM_MANAGER_NETWORK (ret);
  else
    return NULL;
}


/**
 * system_manager_network_proxy_new_for_bus:
 * @bus_type: A #GBusType.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: A bus name (well-known or unique).
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied.
 * @user_data: User data to pass to @callback.
 *
 * Like system_manager_network_proxy_new() but takes a #GBusType instead of a #GDBusConnection.
 *
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call system_manager_network_proxy_new_for_bus_finish() to get the result of the operation.
 *
 * See system_manager_network_proxy_new_for_bus_sync() for the synchronous, blocking version of this constructor.
 */
void
system_manager_network_proxy_new_for_bus (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data)
{
  g_async_initable_new_async (TYPE_SYSTEM_MANAGER_NETWORK_PROXY, G_PRIORITY_DEFAULT, cancellable, callback, user_data, "g-flags", flags, "g-name", name, "g-bus-type", bus_type, "g-object-path", object_path, "g-interface-name", "org.freedesktop.SystemManager.Network", NULL);
}

/**
 * system_manager_network_proxy_new_for_bus_finish:
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to system_manager_network_proxy_new_for_bus().
 * @error: Return location for error or %NULL
 *
 * Finishes an operation started with system_manager_network_proxy_new_for_bus().
 *
 * Returns: (transfer full) (type SystemManagerNetworkProxy): The constructed proxy object or %NULL if @error is set.
 */
SystemManagerNetwork *
system_manager_network_proxy_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error)
{
  GObject *ret;
  GObject *source_object;
  source_object = g_async_result_get_source_object (res);
  ret = g_async_initable_new_finish (G_ASYNC_INITABLE (source_object), res, error);
  g_object_unref (source_object);
  if (ret != NULL)
    return SYSTEM_MANAGER_NETWORK (ret);
  else
    return NULL;
}

/**
 * system_manager_network_proxy_new_for_bus_sync:
 * @bus_type: A #GBusType.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: A bus name (well-known or unique).
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL
 *
 * Like system_manager_network_proxy_new_sync() but takes a #GBusType instead of a #GDBusConnection.
 *
 * The calling thread is blocked until a reply is received.
 *
 * See system_manager_network_proxy_new_for_bus() for the asynchronous version of this constructor.
 *
 * Returns: (transfer full) (type SystemManagerNetworkProxy): The constructed proxy object or %NULL if @error is set.
 */
SystemManagerNetwork *
system_manager_network_proxy_new_for_bus_sync (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error)
{
  GInitable *ret;
  ret = g_initable_new (TYPE_SYSTEM_MANAGER_NETWORK_PROXY, cancellable, error, "g-flags", flags, "g-name", name, "g-bus-type", bus_type, "g-object-path", object_path, "g-interface-name", "org.freedesktop.SystemManager.Network", NULL);
  if (ret != NULL)
    return SYSTEM_MANAGER_NETWORK (ret);
  else
    return NULL;
}


/* ------------------------------------------------------------------------ */

/**
 * SystemManagerNetworkSkeleton:
 *
 * The #SystemManagerNetworkSkeleton structure contains only private data and should only be accessed using the provided API.
 */

/**
 * SystemManagerNetworkSkeletonClass:
 * @parent_class: The parent class.
 *
 * Class structure for #SystemManagerNetworkSkeleton.
 */

struct _SystemManagerNetworkSkeletonPrivate
{
  GValue *properties;
  GList *changed_properties;
  GSource *changed_properties_idle_source;
  GMainContext *context;
  GMutex lock;
};

static void
_system_manager_network_skeleton_handle_method_call (
  GDBusConnection *connection G_GNUC_UNUSED,
  const gchar *sender G_GNUC_UNUSED,
  const gchar *object_path G_GNUC_UNUSED,
  const gchar *interface_name,
  const gchar *method_name,
  GVariant *parameters,
  GDBusMethodInvocation *invocation,
  gpointer user_data)
{
  SystemManagerNetworkSkeleton *skeleton = SYSTEM_MANAGER_NETWORK_SKELETON (user_data);
  _ExtendedGDBusMethodInfo *info;
  GVariantIter iter;
  GVariant *child;
  GValue *paramv;
  guint num_params;
  guint num_extra;
  guint n;
  guint signal_id;
  GValue return_value = G_VALUE_INIT;
  info = (_ExtendedGDBusMethodInfo *) g_dbus_method_invocation_get_method_info (invocation);
  g_assert (info != NULL);
  num_params = g_variant_n_children (parameters);
  num_extra = info->pass_fdlist ? 3 : 2;  paramv = g_new0 (GValue, num_params + num_extra);
  n = 0;
  g_value_init (&paramv[n], TYPE_SYSTEM_MANAGER_NETWORK);
  g_value_set_object (&paramv[n++], skeleton);
  g_value_init (&paramv[n], G_TYPE_DBUS_METHOD_INVOCATION);
  g_value_set_object (&paramv[n++], invocation);
  if (info->pass_fdlist)
    {
#ifdef G_OS_UNIX
      g_value_init (&paramv[n], G_TYPE_UNIX_FD_LIST);
      g_value_set_object (&paramv[n++], g_dbus_message_get_unix_fd_list (g_dbus_method_invocation_get_message (invocation)));
#else
      g_assert_not_reached ();
#endif
    }
  g_variant_iter_init (&iter, parameters);
  while ((child = g_variant_iter_next_value (&iter)) != NULL)
    {
      _ExtendedGDBusArgInfo *arg_info = (_ExtendedGDBusArgInfo *) info->parent_struct.in_args[n - num_extra];
      if (arg_info->use_gvariant)
        {
          g_value_init (&paramv[n], G_TYPE_VARIANT);
          g_value_set_variant (&paramv[n], child);
          n++;
        }
      else
        g_dbus_gvariant_to_gvalue (child, &paramv[n++]);
      g_variant_unref (child);
    }
  signal_id = g_signal_lookup (info->signal_name, TYPE_SYSTEM_MANAGER_NETWORK);
  g_value_init (&return_value, G_TYPE_BOOLEAN);
  g_signal_emitv (paramv, signal_id, 0, &return_value);
  if (!g_value_get_boolean (&return_value))
    g_dbus_method_invocation_return_error (invocation, G_DBUS_ERROR, G_DBUS_ERROR_UNKNOWN_METHOD, "Method %s is not implemented on interface %s", method_name, interface_name);
  g_value_unset (&return_value);
  for (n = 0; n < num_params + num_extra; n++)
    g_value_unset (&paramv[n]);
  g_free (paramv);
}

static GVariant *
_system_manager_network_skeleton_handle_get_property (
  GDBusConnection *connection G_GNUC_UNUSED,
  const gchar *sender G_GNUC_UNUSED,
  const gchar *object_path G_GNUC_UNUSED,
  const gchar *interface_name G_GNUC_UNUSED,
  const gchar *property_name,
  GError **error,
  gpointer user_data)
{
  SystemManagerNetworkSkeleton *skeleton = SYSTEM_MANAGER_NETWORK_SKELETON (user_data);
  GValue value = G_VALUE_INIT;
  GParamSpec *pspec;
  _ExtendedGDBusPropertyInfo *info;
  GVariant *ret;
  ret = NULL;
  info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_system_manager_network_interface_info.parent_struct, property_name);
  g_assert (info != NULL);
  pspec = g_object_class_find_property (G_OBJECT_GET_CLASS (skeleton), info->hyphen_name);
  if (pspec == NULL)
    {
      g_set_error (error, G_DBUS_ERROR, G_DBUS_ERROR_INVALID_ARGS, "No property with name %s", property_name);
    }
  else
    {
      g_value_init (&value, pspec->value_type);
      g_object_get_property (G_OBJECT (skeleton), info->hyphen_name, &value);
      ret = g_dbus_gvalue_to_gvariant (&value, G_VARIANT_TYPE (info->parent_struct.signature));
      g_value_unset (&value);
    }
  return ret;
}

static gboolean
_system_manager_network_skeleton_handle_set_property (
  GDBusConnection *connection G_GNUC_UNUSED,
  const gchar *sender G_GNUC_UNUSED,
  const gchar *object_path G_GNUC_UNUSED,
  const gchar *interface_name G_GNUC_UNUSED,
  const gchar *property_name,
  GVariant *variant,
  GError **error,
  gpointer user_data)
{
  SystemManagerNetworkSkeleton *skeleton = SYSTEM_MANAGER_NETWORK_SKELETON (user_data);
  GValue value = G_VALUE_INIT;
  GParamSpec *pspec;
  _ExtendedGDBusPropertyInfo *info;
  gboolean ret;
  ret = FALSE;
  info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_system_manager_network_interface_info.parent_struct, property_name);
  g_assert (info != NULL);
  pspec = g_object_class_find_property (G_OBJECT_GET_CLASS (skeleton), info->hyphen_name);
  if (pspec == NULL)
    {
      g_set_error (error, G_DBUS_ERROR, G_DBUS_ERROR_INVALID_ARGS, "No property with name %s", property_name);
    }
  else
    {
      if (info->use_gvariant)
        g_value_set_variant (&value, variant);
      else
        g_dbus_gvariant_to_gvalue (variant, &value);
      g_object_set_property (G_OBJECT (skeleton), info->hyphen_name, &value);
      g_value_unset (&value);
      ret = TRUE;
    }
  return ret;
}

static const GDBusInterfaceVTable _system_manager_network_skeleton_vtable =
{
  _system_manager_network_skeleton_handle_method_call,
  _system_manager_network_skeleton_handle_get_property,
  _system_manager_network_skeleton_handle_set_property,
  {NULL}
};

static GDBusInterfaceInfo *
system_manager_network_skeleton_dbus_interface_get_info (GDBusInterfaceSkeleton *skeleton G_GNUC_UNUSED)
{
  return system_manager_network_interface_info ();
}

static GDBusInterfaceVTable *
system_manager_network_skeleton_dbus_interface_get_vtable (GDBusInterfaceSkeleton *skeleton G_GNUC_UNUSED)
{
  return (GDBusInterfaceVTable *) &_system_manager_network_skeleton_vtable;
}

static GVariant *
system_manager_network_skeleton_dbus_interface_get_properties (GDBusInterfaceSkeleton *_skeleton)
{
  SystemManagerNetworkSkeleton *skeleton = SYSTEM_MANAGER_NETWORK_SKELETON (_skeleton);

  GVariantBuilder builder;
  guint n;
  g_variant_builder_init (&builder, G_VARIANT_TYPE ("a{sv}"));
  if (_system_manager_network_interface_info.parent_struct.properties == NULL)
    goto out;
  for (n = 0; _system_manager_network_interface_info.parent_struct.properties[n] != NULL; n++)
    {
      GDBusPropertyInfo *info = _system_manager_network_interface_info.parent_struct.properties[n];
      if (info->flags & G_DBUS_PROPERTY_INFO_FLAGS_READABLE)
        {
          GVariant *value;
          value = _system_manager_network_skeleton_handle_get_property (g_dbus_interface_skeleton_get_connection (G_DBUS_INTERFACE_SKELETON (skeleton)), NULL, g_dbus_interface_skeleton_get_object_path (G_DBUS_INTERFACE_SKELETON (skeleton)), "org.freedesktop.SystemManager.Network", info->name, NULL, skeleton);
          if (value != NULL)
            {
              g_variant_take_ref (value);
              g_variant_builder_add (&builder, "{sv}", info->name, value);
              g_variant_unref (value);
            }
        }
    }
out:
  return g_variant_builder_end (&builder);
}

static void
system_manager_network_skeleton_dbus_interface_flush (GDBusInterfaceSkeleton *_skeleton)
{
}

static void system_manager_network_skeleton_iface_init (SystemManagerNetworkIface *iface);
#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_38
G_DEFINE_TYPE_WITH_CODE (SystemManagerNetworkSkeleton, system_manager_network_skeleton, G_TYPE_DBUS_INTERFACE_SKELETON,
                         G_ADD_PRIVATE (SystemManagerNetworkSkeleton)
                         G_IMPLEMENT_INTERFACE (TYPE_SYSTEM_MANAGER_NETWORK, system_manager_network_skeleton_iface_init));

#else
G_DEFINE_TYPE_WITH_CODE (SystemManagerNetworkSkeleton, system_manager_network_skeleton, G_TYPE_DBUS_INTERFACE_SKELETON,
                         G_IMPLEMENT_INTERFACE (TYPE_SYSTEM_MANAGER_NETWORK, system_manager_network_skeleton_iface_init));

#endif
static void
system_manager_network_skeleton_finalize (GObject *object)
{
  SystemManagerNetworkSkeleton *skeleton = SYSTEM_MANAGER_NETWORK_SKELETON (object);
  g_list_free_full (skeleton->priv->changed_properties, (GDestroyNotify) _changed_property_free);
  if (skeleton->priv->changed_properties_idle_source != NULL)
    g_source_destroy (skeleton->priv->changed_properties_idle_source);
  g_main_context_unref (skeleton->priv->context);
  g_mutex_clear (&skeleton->priv->lock);
  G_OBJECT_CLASS (system_manager_network_skeleton_parent_class)->finalize (object);
}

static void
system_manager_network_skeleton_init (SystemManagerNetworkSkeleton *skeleton)
{
#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_38
  skeleton->priv = system_manager_network_skeleton_get_instance_private (skeleton);
#else
  skeleton->priv = G_TYPE_INSTANCE_GET_PRIVATE (skeleton, TYPE_SYSTEM_MANAGER_NETWORK_SKELETON, SystemManagerNetworkSkeletonPrivate);
#endif

  g_mutex_init (&skeleton->priv->lock);
  skeleton->priv->context = g_main_context_ref_thread_default ();
}

static void
system_manager_network_skeleton_class_init (SystemManagerNetworkSkeletonClass *klass)
{
  GObjectClass *gobject_class;
  GDBusInterfaceSkeletonClass *skeleton_class;

  gobject_class = G_OBJECT_CLASS (klass);
  gobject_class->finalize = system_manager_network_skeleton_finalize;

  skeleton_class = G_DBUS_INTERFACE_SKELETON_CLASS (klass);
  skeleton_class->get_info = system_manager_network_skeleton_dbus_interface_get_info;
  skeleton_class->get_properties = system_manager_network_skeleton_dbus_interface_get_properties;
  skeleton_class->flush = system_manager_network_skeleton_dbus_interface_flush;
  skeleton_class->get_vtable = system_manager_network_skeleton_dbus_interface_get_vtable;

#if GLIB_VERSION_MAX_ALLOWED < GLIB_VERSION_2_38
  g_type_class_add_private (klass, sizeof (SystemManagerNetworkSkeletonPrivate));
#endif
}

static void
system_manager_network_skeleton_iface_init (SystemManagerNetworkIface *iface)
{
}

/**
 * system_manager_network_skeleton_new:
 *
 * Creates a skeleton object for the D-Bus interface <link linkend="gdbus-interface-org-freedesktop-SystemManager-Network.top_of_page">org.freedesktop.SystemManager.Network</link>.
 *
 * Returns: (transfer full) (type SystemManagerNetworkSkeleton): The skeleton object.
 */
SystemManagerNetwork *
system_manager_network_skeleton_new (void)
{
  return SYSTEM_MANAGER_NETWORK (g_object_new (TYPE_SYSTEM_MANAGER_NETWORK_SKELETON, NULL));
}

